#!/bin/zsh


#   git commit-plan -d <message><tab completion>
# option to remove a message from the commit-plan

echo
echo "Commit-Plan:"
echo " - Add your Commit messages."
echo " - Press <ENTER> to continue."
echo " - Enter an empty message to Finish."
echo

commit_plans=()

while true; do
    echo -n " => "
    read -r plan < /dev/tty
    # if plan is empty
    if [[ -z "$plan" ]]; then
        break;
    else
        commit_plans+=("$plan")
    fi
done

# Display collected commit-plans
echo "You entered the following commit-plans:"
for plan in "${commit_plans[@]}"; do
    echo "- $plan"
done

no_spaces=(${commit_plans[@]// /_})
commit_data=${(j:%:)no_spaces}
echo "$commit_data"

git config "branch.${$(git symbolic-ref --short HEAD)}.commit-plan" "$commit_data"
